### ISSUE TITLE
Deep Linking on Android is not working

### ISSUE THREAD

**Issue by pksnz** [loonix/capacitor-oauth2-azure-example#3] opened 2021-07-01 05:56 UTC
**Describe the bug**
Deep Linking on Android is not working

**To Reproduce**
1. Implement Android as per instructions on GitHub.
2. Provides user/pass on B2C screen presented.
3. After authentication the screen doesn't redirect/go back to the main intent.

**Expected behavior**
The Login intent should close after successful authentication and the Access Token is generated.

**Screenshots**
Here is an example I got from chrome://inspect
![image](https://user-images.githubusercontent.com/63991552/124072538-f7a91380-da94-11eb-83d6-dde19fb7aa2d.png)

I also tried changing the Scheme to use com.mydomain.app://oauth and it has the same behaviour.

**Smartphone (please complete the following information):**
 - Device: Android Emulator / Samsung S8
 - OS: Android 9

**Additional context**
I have checked issues [96](https://github.com/moberwasserlechner/capacitor-oauth2/issues/96) and [91](https://github.com/moberwasserlechner/capacitor-oauth2/issues/91) and no luck.
Appreciate any help on this.

**Comment by Ermag** [comment] 2021-07-08 15:33
Facing the exact same issue, any luck finding the root cause?

**Update: I managed to solve it, here is how:**
1. Change the value for the `redirectUrl` field in the `oauth2Options` as follows:
  From --> `redirectUrl: 'com.your.appid://oauth/redirect, `
  To --> `redirectUrl: 'msauth.com.your.appid://auth'`
2. Change the value for the `appAuthRedirectScheme` in the _android/app/build.gradle_ as follows:
  From --> `"appAuthRedirectScheme": "com.your.appid"`
  To --> `"appAuthRedirectScheme": "msauth.com.your.appid"`

**Comment by pksnz** [comment] 2021-07-17 09:51
Thanks @Ermag. That worked!

**Comment by loonix** [comment] 2021-09-16 15:34
Seems like you guys managed to solve this, closing this ticket. (Sorry I only saw this now and honestly I moved to flutter, so much better)

**Closed as completed by loonix** 2021-09-16 15:34 UTC
